' generated.tables: rule, adaptation, commitment, constant and telemetry tables and the phase
' dispatch. Generated by strategy_basic.py from the source; do not edit.


SUB st__init()
  st_commitment__min_hold = 0
  st_commitment__preempt_margin = 0
  st_commitment__interrupt_at = 1001
  st__role_role = 0
  IF selfId = 0 OR selfId = 1 OR selfId = 2 OR selfId = 3 OR selfId = 4 OR selfId = 5 OR selfId = 6 OR selfId = 7 OR selfId = 8 OR selfId = 9 OR selfId = 10 OR selfId = 11 OR selfId = 12 OR selfId = 13 OR selfId = 14 OR selfId = 15 THEN
    st__role_role = 1
  END IF
  rt__n_rules = 1
  rt__def(1) = 100
  rt__prio(1) = 100
  rt__rcap(1) = 1
  rt__n_adapt = 0
  rt__min_hold = st_commitment__min_hold
  rt__margin = st_commitment__preempt_margin
  rt__interrupt = st_commitment__interrupt_at
  rt__n_sits = 0
  rt__n_words = 1
END SUB

SUB st__receive()
END SUB

SUB st__knowledge()
  k_position__update()
END SUB

SUB st__situations()
END SUB

SUB st__adapt()
END SUB

SUB st__conditions()
  rt__ok(1) = 1
END SUB

SUB st__bind()
  rt__in0 = 0
  rt__in1 = 0
  rt__in2 = 0
END SUB

SUB st__start()
  IF rt__cap = 1 THEN
    c_idle__status = 0
    c_idle__cond = 0
    c_idle__start()
  END IF
END SUB

SUB st__tick()
  IF rt__cap = 1 THEN
    c_idle__tick()
    rt__status = c_idle__status
    rt__cond = c_idle__cond
  END IF
  rt__valid = 0
  IF rt__cap = 1 THEN
    IF rt__status = 0 THEN
      rt__valid = 1
    END IF
  END IF
  IF rt__valid = 0 THEN
    rt__status = 2
    rt__cond = -1
  END IF
END SUB

SUB st__send()
END SUB

SUB st__beliefs()
  IF telemetryOff = 0 AND worldTick MOD 24 = 0 THEN
    PRINT "PWB v=2 t="; worldTick; " k=1 d="; k_position__x
    rt__pe = rt__pe + 5
    rt__pb = rt__pb + 40
  END IF
END SUB
