' generated.tables: rule, adaptation, commitment, constant and telemetry tables and the phase
' dispatch. Generated by strategy_basic.py from the source; do not edit.


SUB st__init()
  k_opening_signature__classify_tick = 360
  k_counter_phase__start_tick = 360
  k_counter_phase__earliest_release = 420
  k_counter_phase__stage_deadline = 960
  k_counter_phase__counter_duration = 240
  k_counter_phase__split_distance_sq = 4000000
  k_self_motion__teleport_step = 60
  k_squad_target__progress_period = 72
  k_squad_target__stall_sq = 40000
  k_squad_target__far_sq = 160000
  k_squad_target__avoid_ticks = 360
  k_squad_target__ref_offset = 1500
  k_squad_target__mirror_y = 4000
  k_squad_target__neutral_bonus = 20000
  k_squad_target__avoid_penalty = 4000000
  k_contacts__hp_weight = 160000
  k_contacts__carrier_bonus = 2500000
  k_contacts__former_range_sq = 27562500
  k_contacts__near_foe_sq = 6760000
  k_contacts__near_friend_sq = 1440000
  k_pickups__memory_ticks = 240
  k_pickups__reach_sq = 4840000
  k_pickups__arrive_sq = 10000
  s_supply_worth__fight_clear_sq = 1440000
  s_central_opening__opening_ticks = 720
  sk_motor__wet_cost = 6
  sk_motor__lead_ticks = 6
  sk_motor__drift_ticks = 5
  sk_motor__gun_wait_light = 25
  sk_motor__gun_wait_heavy = 73
  sk_motor__spray_range_sq = 640000
  c_refuse_counter__safe_forward_cm = 1200
  c_refuse_counter__stage_forward_cm = 900
  c_refuse_counter__row_gap_cm = 500
  c_refuse_counter__lane_gap_cm = 600
  c_refuse_counter__counter_back_cm = 600
  c_refuse_counter__dry_step_cm = 100
  c_refuse_counter__dry_steps = 16
  c_refuse_counter__hold_sq = 14400
  c_central_opening__cover_back_cm = 500
  c_central_opening__bank_offset_cm = 600
  c_central_opening__dry_step_cm = 100
  c_central_opening__dry_steps = 8
  c_central_opening__hold_sq = 14400
  c_take_heart__hold_sq = 8100
  c_take_heart__quiet_sq = 810000
  c_cover_heart__capture_sq = 19600
  c_cover_heart__step_in_sq = 640000
  c_cover_heart__idle_limit = 96
  c_cover_heart__post_x = 3200
  c_cover_heart__post_y = 2000
  c_cover_heart__post_shift = 1200
  c_cover_heart__post_radius = 90
  c_cover_heart__hold_sq = 8100
  c_cover_heart__quiet_sq = 810000
  c_default_goal__quiet_sq = 810000
  c_resupply__quiet_sq = 810000
  c_fall_back__quiet_sq = 810000
  st_commitment__min_hold = 0
  st_commitment__preempt_margin = 0
  st_commitment__interrupt_at = 0
  st__role_squad = 0
  IF selfId = 0 OR selfId = 1 OR selfId = 2 OR selfId = 3 OR selfId = 8 OR selfId = 9 OR selfId = 10 OR selfId = 11 THEN
    st__role_squad = 1
  END IF
  IF selfId = 4 OR selfId = 5 OR selfId = 6 OR selfId = 7 OR selfId = 12 OR selfId = 13 OR selfId = 14 OR selfId = 15 THEN
    st__role_squad = 2
  END IF
  rt__n_rules = 7
  rt__def(1) = 400
  rt__prio(1) = 400
  rt__rcap(1) = 7
  rt__def(2) = 360
  rt__prio(2) = 360
  rt__rcap(2) = 1
  rt__def(3) = 350
  rt__prio(3) = 350
  rt__rcap(3) = 2
  rt__def(4) = 300
  rt__prio(4) = 300
  rt__rcap(4) = 6
  rt__def(5) = 200
  rt__prio(5) = 200
  rt__rcap(5) = 3
  rt__def(6) = 200
  rt__prio(6) = 200
  rt__rcap(6) = 4
  rt__def(7) = 100
  rt__prio(7) = 100
  rt__rcap(7) = 5
  rt__n_adapt = 0
  rt__min_hold = st_commitment__min_hold
  rt__margin = st_commitment__preempt_margin
  rt__interrupt = st_commitment__interrupt_at
  rt__n_sits = 5
  rt__n_words = 1
  sk_motor__init()
  k_opening_signature__init()
  k_counter_phase__init()
  k_self_motion__init()
END SUB

SUB st__receive()
END SUB

SUB st__decoded()
END SUB

SUB st__knowledge()
  k_opening_signature__update()
  k_counter_phase__update()
  k_self_motion__update()
  k_squad_target__update()
  k_contacts__update()
  k_pickups__update()
END SUB

SUB st__situations()
  s_losing_fight__eval()
  rt__flag(1) = 0
  IF s_losing_fight__on <> 0 THEN
    rt__flag(1) = 1
  END IF
  s_supply_worth__eval()
  rt__flag(2) = 0
  IF s_supply_worth__on <> 0 THEN
    rt__flag(2) = 1
  END IF
  s_has_target_heart__eval()
  rt__flag(3) = 0
  IF s_has_target_heart__on <> 0 THEN
    rt__flag(3) = 1
  END IF
  s_central_opening__eval()
  rt__flag(4) = 0
  IF s_central_opening__on <> 0 THEN
    rt__flag(4) = 1
  END IF
  s_refuse_counter__eval()
  rt__flag(5) = 0
  IF s_refuse_counter__on <> 0 THEN
    rt__flag(5) = 1
  END IF
END SUB

SUB st__adapt()
END SUB

SUB st__conditions()
  rt__ok(1) = rt__flag(1)
  rt__ok(2) = rt__flag(5)
  rt__ok(3) = rt__flag(4)
  rt__ok(4) = rt__flag(2)
  rt__ok(5) = (rt__flag(3) AND (st__role_squad = 1))
  rt__ok(6) = (rt__flag(3) AND (st__role_squad = 2))
  rt__ok(7) = 1
END SUB

SUB st__bind()
  rt__in0 = 0
  rt__in1 = 0
  rt__in2 = 0
END SUB

SUB st__start()
  IF rt__cap = 1 THEN
    c_refuse_counter__status = 0
    c_refuse_counter__cond = 0
    c_refuse_counter__start()
  END IF
  IF rt__cap = 2 THEN
    c_central_opening__status = 0
    c_central_opening__cond = 0
    c_central_opening__start()
  END IF
  IF rt__cap = 3 THEN
    c_take_heart__status = 0
    c_take_heart__cond = 0
    c_take_heart__start()
  END IF
  IF rt__cap = 4 THEN
    c_cover_heart__status = 0
    c_cover_heart__cond = 0
    c_cover_heart__start()
  END IF
  IF rt__cap = 5 THEN
    c_default_goal__status = 0
    c_default_goal__cond = 0
    c_default_goal__start()
  END IF
  IF rt__cap = 6 THEN
    c_resupply__status = 0
    c_resupply__cond = 0
    c_resupply__start()
  END IF
  IF rt__cap = 7 THEN
    c_fall_back__status = 0
    c_fall_back__cond = 0
    c_fall_back__start()
  END IF
END SUB

SUB st__tick()
  IF rt__cap = 1 THEN
    c_refuse_counter__tick()
    rt__status = c_refuse_counter__status
    rt__cond = c_refuse_counter__cond
  END IF
  IF rt__cap = 2 THEN
    c_central_opening__tick()
    rt__status = c_central_opening__status
    rt__cond = c_central_opening__cond
  END IF
  IF rt__cap = 3 THEN
    c_take_heart__tick()
    rt__status = c_take_heart__status
    rt__cond = c_take_heart__cond
  END IF
  IF rt__cap = 4 THEN
    c_cover_heart__tick()
    rt__status = c_cover_heart__status
    rt__cond = c_cover_heart__cond
  END IF
  IF rt__cap = 5 THEN
    c_default_goal__tick()
    rt__status = c_default_goal__status
    rt__cond = c_default_goal__cond
  END IF
  IF rt__cap = 6 THEN
    c_resupply__tick()
    rt__status = c_resupply__status
    rt__cond = c_resupply__cond
  END IF
  IF rt__cap = 7 THEN
    c_fall_back__tick()
    rt__status = c_fall_back__status
    rt__cond = c_fall_back__cond
  END IF
  rt__valid = 0
  IF rt__cap = 1 THEN
    IF rt__status = 0 THEN
      rt__valid = 1
    END IF
  END IF
  IF rt__cap = 2 THEN
    IF rt__status = 0 THEN
      rt__valid = 1
    END IF
  END IF
  IF rt__cap = 3 THEN
    IF rt__status = 0 THEN
      rt__valid = 1
    END IF
  END IF
  IF rt__cap = 4 THEN
    IF rt__status = 0 THEN
      rt__valid = 1
    END IF
  END IF
  IF rt__cap = 5 THEN
    IF rt__status = 0 THEN
      rt__valid = 1
    END IF
  END IF
  IF rt__cap = 6 THEN
    IF rt__status = 0 THEN
      rt__valid = 1
    END IF
  END IF
  IF rt__cap = 7 THEN
    IF rt__status = 0 THEN
      rt__valid = 1
    END IF
  END IF
  IF rt__valid = 0 THEN
    rt__status = 2
    rt__cond = -1
  END IF
END SUB

SUB st__send()
  com_status_call__sent = 0
  com_status_call__send()
  IF com_status_call__sent <> 0 AND telemetryOff = 0 THEN
    PRINT "PWC v=2 t="; worldTick; " m=1 s=1 w="; selfId; " d="; com_status_call__phase; ","; com_status_call__trigger; ","; com_status_call__release_tick; ","; com_status_call__stage_ticks; ","; com_status_call__counter_ticks; ","; com_status_call__map_known
    rt__pe = rt__pe + 17
    rt__pb = rt__pb + 118
  END IF
  com_grenade_out__sent = 0
  com_grenade_out__send()
  IF com_grenade_out__sent <> 0 AND telemetryOff = 0 THEN
    PRINT "PWC v=2 t="; worldTick; " m=2 s=1 w="; selfId; " d=0"
    rt__pe = rt__pe + 6
    rt__pb = rt__pb + 48
  END IF
END SUB

SUB st__beliefs()
  IF telemetryOff = 0 AND worldTick MOD 24 = 0 THEN
    PRINT "PWB v=2 t="; worldTick; " k=4 d="; k_squad_target__objective; ","; k_squad_target__idle_capture
    rt__pe = rt__pe + 7
    rt__pb = rt__pb + 52
  END IF
  IF telemetryOff = 0 AND worldTick MOD 24 = 1 THEN
    PRINT "PWB v=2 t="; worldTick; " k=5 d="; k_contacts__best; ","; k_contacts__foes_near; ","; k_contacts__friends_near; ","; k_contacts__range_rejected_total
    rt__pe = rt__pe + 11
    rt__pb = rt__pb + 76
  END IF
  IF telemetryOff = 0 AND worldTick MOD 24 = 2 THEN
    PRINT "PWB v=2 t="; worldTick; " k=6 d="; k_pickups__nearest; ","; k_pickups__hp_cap; ","; k_pickups__hp_changed_total
    rt__pe = rt__pe + 9
    rt__pb = rt__pb + 64
  END IF
END SUB

SUB st__pwd_print()
  PRINT "PWD v=2 t="; worldTick; " r="; rt__rule; " c="; rt__cap; " i=0,0,0 h="; rt__held; " p=0 f="; rt__fw(0)
  rt__pe = rt__pe + 11
  rt__pb = rt__pb + 51
END SUB

SUB st__flush()
END SUB
