' generated.tables: rule, adaptation, commitment, constant and telemetry tables and the phase
' dispatch. Generated by strategy_basic.py from the source; do not edit.

DIM k_contacts__friend(15)
DIM k_contacts__hostile(15)
DIM k_comms_danger__grenade_x(3)
DIM k_comms_danger__grenade_y(3)
DIM k_comms_danger__grenade_until(3)
DIM com_disguise_friend__packet(1)
DIM com_disguise_friend__df_x(15)
DIM com_disguise_friend__df_y(15)
DIM com_disguise_friend__df_until(15)
DIM com_disguise_alert__packet(1)
DIM com_disguise_alert__xa_s1(15)
DIM com_disguise_alert__xa_x1(15)
DIM com_disguise_alert__xa_y1(15)
DIM com_disguise_alert__xa_t1(15)
DIM com_disguise_alert__xa_s2(15)
DIM com_disguise_alert__xa_x2(15)
DIM com_disguise_alert__xa_y2(15)
DIM com_disguise_alert__xa_t2(15)
DIM com_disguise_alert__xa_amb(15)
DIM com_focus_call__packet(1)
DIM com_glory_seen__packet(1)
DIM com_glory_seen__gl_x(7)
DIM com_glory_seen__gl_y(7)
DIM com_glory_seen__gl_until(7)
DIM com_glory_seen__gl_t(7)
DIM com_enemy_sighting__packet(1)
DIM com_enemy_sighting__ht_x(15)
DIM com_enemy_sighting__ht_y(15)
DIM com_enemy_sighting__ht_t(15)
DIM com_enemy_sighting__ht_until(15)
DIM com_grenade_warning__packet(1)
DIM com_grenade_warning__gz_x(3)
DIM com_grenade_warning__gz_y(3)
DIM com_grenade_warning__gz_until(3)
DIM com_under_fire__packet(1)
DIM com_pickup_taken__packet(1)
DIM com_pickup_taken__rk_until(63)
DIM com_pickup_taken__rk_t(63)
DIM com_pickup_ready__packet(1)
DIM com_pickup_ready__rr_x(63)
DIM com_pickup_ready__rr_y(63)
DIM com_pickup_ready__rr_kind(63)
DIM com_pickup_ready__rr_t(63)

SUB st__init()
  k_self_motion__teleport_step = 60
  k_squad_target__progress_period = 72
  k_squad_target__stall_sq = 40000
  k_squad_target__far_sq = 160000
  k_squad_target__avoid_ticks = 360
  k_squad_target__ref_offset = 1500
  k_squad_target__mirror_y = 4000
  k_squad_target__neutral_bonus = 20000
  k_squad_target__avoid_penalty = 4000000
  k_contacts__hp_weight = 160000
  k_contacts__carrier_bonus = 2500000
  k_contacts__range_sq = 27562500
  k_contacts__near_foe_sq = 6760000
  k_contacts__near_friend_sq = 1440000
  k_contacts__engage_range_sq = 4549689
  k_pickups__memory_ticks = 240
  k_pickups__reach_sq = 4840000
  k_pickups__arrive_sq = 10000
  k_pickups__take_radius_sq = 14400
  k_pickups__grenade_delay = 120
  k_pickups__supply_delay = 720
  k_comms_danger__clear_radius = 450 ' @tune 250 700 50
  s_supply_worth__fight_clear_sq = 1440000
  sk_motor__wet_cost = 6
  sk_motor__lead_ticks = 6
  sk_motor__drift_ticks = 5
  sk_motor__gun_wait_light = 25
  sk_motor__gun_wait_heavy = 73
  sk_motor__spray_range_sq = 640000
  c_take_heart__hold_sq = 8100
  c_take_heart__quiet_sq = 810000
  c_cover_heart__step_in_sq = 640000
  c_cover_heart__idle_limit = 96
  c_cover_heart__post_x = 3200
  c_cover_heart__post_y = 2000
  c_cover_heart__post_shift = 1200
  c_cover_heart__post_radius = 90
  c_cover_heart__hold_sq = 8100
  c_cover_heart__quiet_sq = 810000
  c_default_goal__quiet_sq = 810000
  c_resupply__quiet_sq = 810000
  c_fall_back__quiet_sq = 810000
  st_commitment__min_hold = 0
  st_commitment__preempt_margin = 0
  st_commitment__interrupt_at = 0
  com_disguise_friend__d_refresh = 24 ' @tune 12 72 12
  com_disguise_friend__friend_radius = 250 ' @tune 100 500 50
  com_disguise_friend__friend_ttl = 48 ' @tune 24 120 12
  com_disguise_friend__d_range_sq = 1638400
  com_disguise_alert__x_window = 24 ' @tune 12 72 12
  com_disguise_alert__x_distance = 1000 ' @tune 700 1500 100
  com_disguise_alert__x_radius = 300 ' @tune 100 600 50
  com_disguise_alert__disguise_ttl = 72 ' @tune 24 240 24
  com_disguise_alert__x_refresh = 24 ' @tune 12 72 12
  com_focus_call__focus_refresh = 24 ' @tune 12 48 12
  com_focus_call__focus_ttl = 36 ' @tune 12 72 12
  com_focus_call__focus_radius = 400 ' @tune 100 800 50
  com_focus_call__full_hp = 10
  com_glory_seen__h_refresh = 120 ' @tune 48 240 24
  com_glory_seen__h_match = 200
  com_enemy_sighting__e_refresh = 12 ' @tune 6 48 6
  com_enemy_sighting__e_move = 300 ' @tune 100 800 50
  com_enemy_sighting__heard_ttl = 48 ' @tune 24 120 12
  com_grenade_warning__g_move = 200 ' @tune 100 400 50
  com_under_fire__danger_ttl = 48 ' @tune 24 120 12
  com_pickup_taken__event_window = 24 ' @tune 6 48 6
  com_pickup_ready__event_window = 24 ' @tune 6 48 6
  st__role_squad = 0
  IF selfId = 0 OR selfId = 1 OR selfId = 2 OR selfId = 3 OR selfId = 8 OR selfId = 9 OR selfId = 10 OR selfId = 11 THEN
    st__role_squad = 1
  END IF
  IF selfId = 4 OR selfId = 5 OR selfId = 6 OR selfId = 7 OR selfId = 12 OR selfId = 13 OR selfId = 14 OR selfId = 15 THEN
    st__role_squad = 2
  END IF
  rt__n_rules = 5
  rt__def(1) = 400
  rt__prio(1) = 400
  rt__rcap(1) = 5
  rt__def(2) = 300
  rt__prio(2) = 300
  rt__rcap(2) = 4
  rt__def(3) = 200
  rt__prio(3) = 200
  rt__rcap(3) = 1
  rt__def(4) = 200
  rt__prio(4) = 200
  rt__rcap(4) = 2
  rt__def(5) = 100
  rt__prio(5) = 100
  rt__rcap(5) = 3
  rt__n_adapt = 0
  rt__min_hold = st_commitment__min_hold
  rt__margin = st_commitment__preempt_margin
  rt__interrupt = st_commitment__interrupt_at
  rt__n_sits = 3
  rt__n_words = 1
  cm__keys(0) = 7919
  cm__keys(1) = 17431
  cm__keys(2) = 23117
  cm__keys(3) = 1907
  cm__keys(4) = 31
  cm__keys(5) = 73
  cm__max_decode = 8
  cm__min_gap = 6
  sk_motor__init()
  k_self_motion__init()
  k_pickups__init()
  com_focus_call__init()
END SUB

SUB st__receive()
  com_enemy_sighting__got = 0
  com_focus_call__got = 0
  com_grenade_warning__got = 0
  com_under_fire__got = 0
  com_glory_seen__got = 0
  com_pickup_taken__got = 0
  com_pickup_ready__got = 0
  com_disguise_alert__got = 0
  com_disguise_friend__got = 0
  cm__receive()
END SUB

SUB st__decoded()
  IF cm__type = 0 THEN
    com_enemy_sighting__packet(0) = cm__pa
    com_enemy_sighting__packet(1) = cm__pb
    com_enemy_sighting__got = com_enemy_sighting__got + 1
    com_enemy_sighting__from = cm__speaker
    com_enemy_sighting__recv()
  END IF
  IF cm__type = 1 THEN
    com_focus_call__packet(0) = cm__pa
    com_focus_call__packet(1) = cm__pb
    com_focus_call__got = com_focus_call__got + 1
    com_focus_call__from = cm__speaker
    com_focus_call__recv()
  END IF
  IF cm__type = 2 THEN
    com_grenade_warning__packet(0) = cm__pa
    com_grenade_warning__packet(1) = cm__pb
    com_grenade_warning__got = com_grenade_warning__got + 1
    com_grenade_warning__from = cm__speaker
    com_grenade_warning__recv()
  END IF
  IF cm__type = 3 THEN
    com_under_fire__packet(0) = cm__pa
    com_under_fire__packet(1) = cm__pb
    com_under_fire__got = com_under_fire__got + 1
    com_under_fire__from = cm__speaker
    com_under_fire__recv()
  END IF
  IF cm__type = 4 THEN
    com_glory_seen__packet(0) = cm__pa
    com_glory_seen__packet(1) = cm__pb
    com_glory_seen__got = com_glory_seen__got + 1
    com_glory_seen__from = cm__speaker
    com_glory_seen__recv()
  END IF
  IF cm__type = 5 THEN
    com_pickup_taken__packet(0) = cm__pa
    com_pickup_taken__packet(1) = cm__pb
    com_pickup_taken__got = com_pickup_taken__got + 1
    com_pickup_taken__from = cm__speaker
    com_pickup_taken__recv()
  END IF
  IF cm__type = 6 THEN
    com_pickup_ready__packet(0) = cm__pa
    com_pickup_ready__packet(1) = cm__pb
    com_pickup_ready__got = com_pickup_ready__got + 1
    com_pickup_ready__from = cm__speaker
    com_pickup_ready__recv()
  END IF
  IF cm__type = 7 THEN
    com_disguise_alert__packet(0) = cm__pa
    com_disguise_alert__packet(1) = cm__pb
    com_disguise_alert__got = com_disguise_alert__got + 1
    com_disguise_alert__from = cm__speaker
    com_disguise_alert__recv()
  END IF
  IF cm__type = 8 THEN
    com_disguise_friend__packet(0) = cm__pa
    com_disguise_friend__packet(1) = cm__pb
    com_disguise_friend__got = com_disguise_friend__got + 1
    com_disguise_friend__from = cm__speaker
    com_disguise_friend__recv()
  END IF
END SUB

SUB st__knowledge()
  k_self_motion__update()
  k_squad_target__update()
  k_contacts__update()
  k_pickups__update()
  k_comms_danger__update()
  k_glory_hearts__update()
END SUB

SUB st__situations()
  s_losing_fight__eval()
  rt__flag(1) = 0
  IF s_losing_fight__on <> 0 THEN
    rt__flag(1) = 1
  END IF
  s_supply_worth__eval()
  rt__flag(2) = 0
  IF s_supply_worth__on <> 0 THEN
    rt__flag(2) = 1
  END IF
  s_has_target_heart__eval()
  rt__flag(3) = 0
  IF s_has_target_heart__on <> 0 THEN
    rt__flag(3) = 1
  END IF
END SUB

SUB st__adapt()
END SUB

SUB st__conditions()
  rt__ok(1) = rt__flag(1)
  rt__ok(2) = rt__flag(2)
  rt__ok(3) = (rt__flag(3) AND (st__role_squad = 1))
  rt__ok(4) = (rt__flag(3) AND (st__role_squad = 2))
  rt__ok(5) = 1
END SUB

SUB st__bind()
  rt__in0 = 0
  rt__in1 = 0
  rt__in2 = 0
END SUB

SUB st__start()
  IF rt__cap = 1 THEN
    c_take_heart__status = 0
    c_take_heart__cond = 0
    c_take_heart__start()
  END IF
  IF rt__cap = 2 THEN
    c_cover_heart__status = 0
    c_cover_heart__cond = 0
    c_cover_heart__start()
  END IF
  IF rt__cap = 3 THEN
    c_default_goal__status = 0
    c_default_goal__cond = 0
    c_default_goal__start()
  END IF
  IF rt__cap = 4 THEN
    c_resupply__status = 0
    c_resupply__cond = 0
    c_resupply__start()
  END IF
  IF rt__cap = 5 THEN
    c_fall_back__status = 0
    c_fall_back__cond = 0
    c_fall_back__start()
  END IF
END SUB

SUB st__tick()
  IF rt__cap = 1 THEN
    c_take_heart__tick()
    rt__status = c_take_heart__status
    rt__cond = c_take_heart__cond
  END IF
  IF rt__cap = 2 THEN
    c_cover_heart__tick()
    rt__status = c_cover_heart__status
    rt__cond = c_cover_heart__cond
  END IF
  IF rt__cap = 3 THEN
    c_default_goal__tick()
    rt__status = c_default_goal__status
    rt__cond = c_default_goal__cond
  END IF
  IF rt__cap = 4 THEN
    c_resupply__tick()
    rt__status = c_resupply__status
    rt__cond = c_resupply__cond
  END IF
  IF rt__cap = 5 THEN
    c_fall_back__tick()
    rt__status = c_fall_back__status
    rt__cond = c_fall_back__cond
  END IF
  rt__valid = 0
  IF rt__cap = 1 THEN
    IF rt__status = 0 THEN
      rt__valid = 1
    END IF
  END IF
  IF rt__cap = 2 THEN
    IF rt__status = 0 THEN
      rt__valid = 1
    END IF
  END IF
  IF rt__cap = 3 THEN
    IF rt__status = 0 THEN
      rt__valid = 1
    END IF
  END IF
  IF rt__cap = 4 THEN
    IF rt__status = 0 THEN
      rt__valid = 1
    END IF
  END IF
  IF rt__cap = 5 THEN
    IF rt__status = 0 THEN
      rt__valid = 1
    END IF
  END IF
  IF rt__valid = 0 THEN
    rt__status = 2
    rt__cond = -1
  END IF
END SUB

SUB st__send()
  cm__sent = 0
  com_enemy_sighting__sent = 0
  com_focus_call__sent = 0
  com_grenade_warning__sent = 0
  com_under_fire__sent = 0
  com_glory_seen__sent = 0
  com_pickup_taken__sent = 0
  com_pickup_ready__sent = 0
  com_disguise_alert__sent = 0
  com_disguise_friend__sent = 0
  IF cm__sent = 0 THEN
    com_grenade_warning__send()
    com_grenade_warning__sent = cm__sent
    IF com_grenade_warning__sent <> 0 THEN
      com_grenade_warning__packet(0) = cm__pa
      com_grenade_warning__packet(1) = cm__pb
    END IF
  END IF
  IF cm__sent = 0 THEN
    com_disguise_friend__send()
    com_disguise_friend__sent = cm__sent
    IF com_disguise_friend__sent <> 0 THEN
      com_disguise_friend__packet(0) = cm__pa
      com_disguise_friend__packet(1) = cm__pb
    END IF
  END IF
  IF cm__sent = 0 THEN
    com_disguise_alert__send()
    com_disguise_alert__sent = cm__sent
    IF com_disguise_alert__sent <> 0 THEN
      com_disguise_alert__packet(0) = cm__pa
      com_disguise_alert__packet(1) = cm__pb
    END IF
  END IF
  IF cm__sent = 0 THEN
    com_focus_call__send()
    com_focus_call__sent = cm__sent
    IF com_focus_call__sent <> 0 THEN
      com_focus_call__packet(0) = cm__pa
      com_focus_call__packet(1) = cm__pb
    END IF
  END IF
  IF cm__sent = 0 THEN
    com_glory_seen__send()
    com_glory_seen__sent = cm__sent
    IF com_glory_seen__sent <> 0 THEN
      com_glory_seen__packet(0) = cm__pa
      com_glory_seen__packet(1) = cm__pb
    END IF
  END IF
  IF cm__sent = 0 THEN
    com_enemy_sighting__send()
    com_enemy_sighting__sent = cm__sent
    IF com_enemy_sighting__sent <> 0 THEN
      com_enemy_sighting__packet(0) = cm__pa
      com_enemy_sighting__packet(1) = cm__pb
    END IF
  END IF
  IF cm__sent = 0 THEN
    com_under_fire__send()
    com_under_fire__sent = cm__sent
    IF com_under_fire__sent <> 0 THEN
      com_under_fire__packet(0) = cm__pa
      com_under_fire__packet(1) = cm__pb
    END IF
  END IF
  IF cm__sent = 0 THEN
    com_pickup_taken__send()
    com_pickup_taken__sent = cm__sent
    IF com_pickup_taken__sent <> 0 THEN
      com_pickup_taken__packet(0) = cm__pa
      com_pickup_taken__packet(1) = cm__pb
    END IF
  END IF
  IF cm__sent = 0 THEN
    com_pickup_ready__send()
    com_pickup_ready__sent = cm__sent
    IF com_pickup_ready__sent <> 0 THEN
      com_pickup_ready__packet(0) = cm__pa
      com_pickup_ready__packet(1) = cm__pb
    END IF
  END IF
END SUB

SUB st__beliefs()
  IF telemetryOff = 0 AND worldTick MOD 24 = 0 THEN
    PRINT "PWB v=2 t="; worldTick; " k=2 d="; k_squad_target__objective; ","; k_squad_target__idle_capture
    rt__pe = rt__pe + 7
    rt__pb = rt__pb + 52
  END IF
  IF telemetryOff = 0 AND worldTick MOD 24 = 1 THEN
    PRINT "PWB v=2 t="; worldTick; " k=3 d="; k_contacts__best; ","; k_contacts__foes_near; ","; k_contacts__friends_near; ","; k_contacts__focus_used
    rt__pe = rt__pe + 11
    rt__pb = rt__pb + 76
  END IF
  IF telemetryOff = 0 AND worldTick MOD 24 = 2 THEN
    PRINT "PWB v=2 t="; worldTick; " k=4 d="; k_pickups__nearest; ","; k_pickups__taken_id
    rt__pe = rt__pe + 7
    rt__pb = rt__pb + 52
  END IF
  IF telemetryOff = 0 AND worldTick MOD 24 = 3 THEN
    PRINT "PWB v=2 t="; worldTick; " k=5 d="; k_comms_danger__zone_count; ","; k_comms_danger__danger_until
    rt__pe = rt__pe + 7
    rt__pb = rt__pb + 52
  END IF
  IF telemetryOff = 0 AND worldTick MOD 24 = 4 THEN
    PRINT "PWB v=2 t="; worldTick; " k=6 d="; k_glory_hearts__count; ","; k_glory_hearts__nearest_left
    rt__pe = rt__pe + 7
    rt__pb = rt__pb + 52
  END IF
END SUB

SUB st__pwd_print()
  PRINT "PWD v=2 t="; worldTick; " r="; rt__rule; " c="; rt__cap; " i=0,0,0 h="; rt__held; " p=0 f="; rt__fw(0)
  rt__pe = rt__pe + 11
  rt__pb = rt__pb + 50
END SUB

SUB st__flush()
  cm__flush()
END SUB
