"""Probe C: under the real scorer, how much does STYLE vs TOPICALITY matter?

This decides whether the answer/proposal path needs an LLM. The game scores each
challenge question as a first-divergent-token choice between two answers under
the steered judge (`game.py:option_selection_probs`). We reproduce that with the
live worker and compare realistic answer types, generated by the judge itself so
they're not cherry-picked:

  S  = in-style, on-topic   (judge steered to the true style, truncated <=12 tok)
  P  = plain,    on-topic   (UNSTEERED judge, truncated)  -- a styleless opponent
  X  = in-style, off-topic  (true style, but answering a DIFFERENT question)

Head-to-heads under the true style (averaged over both orderings):
  S vs P : does an in-style answer beat a styleless one?      (style dominance)
  X vs P : does pure style beat on-topic-but-plain?           (style alone)
  S vs X : given equal style, does being on-topic matter?     (topicality)

Reads:
  - If S >> P and X >~ P  -> style dominates; a cheap in-style answerer wins.
    LLM in the answer path is likely unnecessary.
  - If S beats P but X loses to P, and S beats X -> topicality matters too; the
    answerer must be on-topic AND in-style (LLM more attractive there).

Run:  uv run python cue_n_woo_lab/probe/probe_scoring.py [--styles N]
"""
from __future__ import annotations

import argparse
import json
import os
import random
import re

import worker_client as wc

HERE = os.path.dirname(__file__)
CONCEPTS = json.load(open(os.path.join(HERE, "concepts.json")))

# Challenge questions + a fixed "other" question to source off-topic style text.
CHALLENGE_QS = [
    "What do you do to relax after a long day?",
    "What advice would you give about handling money?",
]
OTHER_Q = "Describe a storm at sea."

# Candidate answers are truncated to <=12 tokens anyway, so generate them short
# (faster on the slow shared worker). Context answers can be a bit longer.
CAND_TOKENS = 24
CONTEXT_TOKENS = 48

# Private-interview questions used to build the scorer's reference material.
PRIVATE_QS = [
    "Tell me about your morning and what you had for breakfast.",
    "What is something you find beautiful?",
    "How do you feel about rules?",
]

MAX_ANSWER_TOKENS = 12


def truncate(text: str, n: int = MAX_ANSWER_TOKENS) -> str:
    """First sentence-ish, capped to n whitespace tokens; printable, single-spaced."""
    text = text.strip().split("\n")[0]
    # cut at first sentence end if it fits, else hard token cap
    m = re.match(r"^(.{3,}?[.!?])(\s|$)", text)
    if m and len(m.group(1).split()) <= n:
        text = m.group(1)
    toks = re.findall(r"\S+", text)[:n]
    out = " ".join(toks)
    out = re.sub(r"[^ -~]", "", out)  # printable ASCII only
    return out.strip() or "no comment here"


def build_context(style: str) -> str:
    """Reference material = the judge's in-style answers to the private questions,
    formatted like game.py:scoring_context (one player's transcript is enough to
    probe; the real game concatenates both)."""
    answers = wc.generate_batch([(style, q) for q in PRIVATE_QS], max_tokens=CONTEXT_TOKENS)
    lines = ["Reference material:"]
    for i, (q, a) in enumerate(zip(PRIVATE_QS, answers), start=1):
        lines.append(f"Record 1.{i} question: {q}\nRecord 1.{i} answer: {a}")
    return "\n\n".join(lines)


def secret_prob(style: str, context: str, question: str, a: str, b: str) -> float:
    """P the steered judge prefers answer `a` over `b` (averaged over orderings)."""
    return wc.choice_probs(style, context, question, [a, b])[0]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--styles", type=int, default=8)
    ap.add_argument("--seed", type=int, default=3)
    args = ap.parse_args()
    print("worker:", wc.health().get("model_id"))

    rng = random.Random(args.seed)
    style_idx = rng.sample(range(len(CONCEPTS)), min(args.styles, len(CONCEPTS)))

    agg = {"S>P": [], "X>P": [], "S>X": []}
    for si in style_idx:
        style = CONCEPTS[si]
        context = build_context(style)
        X = truncate(wc.generate(style, OTHER_Q, max_tokens=CAND_TOKENS))  # in-style, off-topic (once per style)
        for q in CHALLENGE_QS:
            S = truncate(wc.generate(style, q, max_tokens=CAND_TOKENS))
            P = truncate(wc.generate("", q, max_tokens=CAND_TOKENS))  # unsteered = styleless opponent
            sp = secret_prob(style, context, q, S, P)
            xp = secret_prob(style, context, q, X, P)
            sx = secret_prob(style, context, q, S, X)
            agg["S>P"].append(sp)
            agg["X>P"].append(xp)
            agg["S>X"].append(sx)
            print("=" * 70)
            print(f"[{si}] {style[:46]}")
            print(f"  Q: {q}")
            print(f"  S(style,on-topic): {S!r}")
            print(f"  P(plain,on-topic): {P!r}")
            print(f"  X(style,off-topic):{X!r}")
            print(f"  P(S>P)={sp:.2f}  P(X>P)={xp:.2f}  P(S>X)={sx:.2f}")

    def summarize(key: str) -> str:
        vals = agg[key]
        winrate = sum(1 for v in vals if v > 0.5) / len(vals)
        avg = sum(vals) / len(vals)
        return f"{key}: avg_secret_prob={avg:.2f}  win_rate={winrate:.0%}  (n={len(vals)})"

    print("\n" + "#" * 70)
    print("SUMMARY (secret = first-named; >0.5 means it beats the other)")
    print(" ", summarize("S>P"), "  <- in-style vs styleless")
    print(" ", summarize("X>P"), "  <- pure style (off-topic) vs on-topic plain")
    print(" ", summarize("S>X"), "  <- on-topic vs off-topic (both in-style)")


if __name__ == "__main__":
    main()
